import type {Metadata} from "next";

import Link from "next/link";

import {Toaster} from "@/components/ui/toaster";

import "./globals.css";

import "./fosforos.css";

export const metadata: Metadata = {
  title: "anotadorTruco",
  description: "Generated by colidevs CLI",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] bg-[url(/fondoMadera.jpg)] bg-cover px-4 font-sans antialiased">
        <header className="text-xl font-bold leading-[4rem]">
          <Link href="/">anotadorTruco</Link>
        </header>
        <main className="py-8">{children}</main>
        <Toaster className="px-20" />
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} anotadorTruco
        </footer>
      </body>
    </html>
  );
}
